node {
    stage('Checkout') {
       git branch: 'main', url: '/home/osboxes/Desktop/MayankLocalRepositoryDay3'
    }
    
    stage("Gradle build") {
        sh 'gradle -b mayankchrisdataserviceproject-Day3/build.gradle clean build'
    }
    
    stage('User Acceptance Test') {
	
	def response= input message: 'Is this build good to go?',
		parameters: [choice(choices: 'Yes\nNo',
		description: '', name: 'Pass')]
	
	if(response=="Yes") {
		stage('Deploy') {
		 sh 'gradle -b mayankchrisdataserviceproject-Day3/build.gradle build -x test'
			}
		}
	}
} 


